# Site settings
title: Haohang Xu
email: haohang.xu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Hi!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://haohangxu.github.io" # the base hostname & protocol for your site
github_username:  haohangxu

# Build settings
markdown: kramdown
