permalink:           pretty

# Setup
title:               Haohang Xu
tagline:             ''
description:         'A personal site'
url:                 haohang.me
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Haohang Xu
  url:               haohang.me
  email:             haohang.xu@gmail.com

# Custom vars
version:             1.0.0
