baseURL = "https://haohangxu.github.io"
disablePathToLower = true
languageCode = "en-us"
title = "Haohang Xu"
enableEmoji = true
enableRobotsTXT = true

[params]
  footer = "Haohang Xu"
  description = ""
  avatarURL = "/images/profile.jpg"
  avatarSize = "size-m"
  customHeadHTML = """
    <!-- KaTeX -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.13.16/dist/katex.min.css" integrity="sha384-6LkG2wmY8FK9E0vU9OOr8UvLwsaqUg9SETfpq4uTCN1agNe8HRdE9ABlk+fVx6gZ" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.13.16/dist/katex.min.js" integrity="sha384-31El76TwmbHj4rF9DyLsygbq6xoIobG0W+jqXim+a3dU9W53tdH3A/ngRPxOzzaB" crossorigin="anonymous"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.13.16/dist/contrib/auto-render.min.js" integrity="sha384-vZTG03m+2yp6N6BNi5iM4rW4oIwk5DfcNdFfxkk9ZWpDriOkXX8voJBFrAO7MpVl" crossorigin="anonymous"
        onload="renderMathInElement(document.body);"></script>
  """
  socialIcons = [
    {name = "github", url = "https://github.com/haohangxu" },
    {name = "gitlab", url = "https://gitlab.com/haohang" },
    {name = "spotify", url = "https://open.spotify.com/user/haohang1" },
    {name = "goodreads", url = "https://www.goodreads.com/user/show/71203640-haohang" },
    {name = "linkedin", url = "https://www.linkedin.com/in/haohangxu"},
    {name = "resume", url = "/files/HaohangXu.pdf" },             
  ]

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4

  [[menu.main]]
    identifier = "rss"
    pre = "<span data-feather='rss'></span>"
    url = "/index.xml"
    weight = 5
